Loading pytorch-gpu/py3/1.6.0
  Loading requirement: gcc/8.3.1 cuda/10.2 nccl/2.6.4-1-cuda
    cudnn/7.6.5.32-cuda-10.2 intel-mkl/2020.1 magma/2.5.3-cuda
    openmpi/4.0.2-cuda
++ sed -n 2p parameters_combinations/mnist_classifier_ratio.txt
+ LINE='--gpu_devices 0 --max_iter 100 --batch_size 32 --lr 1e-3 --use_scheduler False --is_default_model False --is_custom_model_BK True --use_VAE True --z_var_size 5 --lambda_BCE 1 --beta 3 --var_hidden_filters_1 32 --var_hidden_filters_2 32 --var_hidden_filters_3 32 --var_kernel_size_1 4 --var_kernel_size_2 4 --var_kernel_size_3 5 --var_stride_size_1 2 --var_stride_size_2 1 --var_stride_size_3 1 --var_hidden_dim 256 --var_three_conv_layer True --exp_name mnist_balanced_dataset_encoder_ratio_min_and_mean_1_2_1_1_VAE_3c_32_5_1'
+ echo --gpu_devices 0 --max_iter 100 --batch_size 32 --lr 1e-3 --use_scheduler False --is_default_model False --is_custom_model_BK True --use_VAE True --z_var_size 5 --lambda_BCE 1 --beta 3 --var_hidden_filters_1 32 --var_hidden_filters_2 32 --var_hidden_filters_3 32 --var_kernel_size_1 4 --var_kernel_size_2 4 --var_kernel_size_3 5 --var_stride_size_1 2 --var_stride_size_2 1 --var_stride_size_3 1 --var_hidden_dim 256 --var_three_conv_layer True --exp_name mnist_balanced_dataset_encoder_ratio_min_and_mean_1_2_1_1_VAE_3c_32_5_1
+ python3 -u main.py --gpu_devices 0 --max_iter 100 --batch_size 32 --lr 1e-3 --use_scheduler False --is_default_model False --is_custom_model_BK True --use_VAE True --z_var_size 5 --lambda_BCE 1 --beta 3 --var_hidden_filters_1 32 --var_hidden_filters_2 32 --var_hidden_filters_3 32 --var_kernel_size_1 4 --var_kernel_size_2 4 --var_kernel_size_3 5 --var_stride_size_1 2 --var_stride_size_2 1 --var_stride_size_3 1 --var_hidden_dim 256 --var_three_conv_layer True --exp_name mnist_balanced_dataset_encoder_ratio_min_and_mean_1_2_1_1_VAE_3c_32_5_1
--- Logging error ---
Traceback (most recent call last):
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 611, in format
    s = self.formatMessage(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 580, in formatMessage
    return self._style.format(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 422, in format
    return self._fmt % record.__dict__
KeyError: 'asc_time'
Call stack:
  File "main.py", line 278, in <module>
    main(args)
  File "main.py", line 30, in main
    net = SolverClassifier(arguments)
  File "/gpfsdswork/projects/rech/rjg/uiu23ko/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 343, in __init__
    self.test_loader_size))
Message: 'Dataset mnist: train with 60000 samples and 10000 test samples'
Arguments: ()
  0%|          | 0/100.0 [00:00<?, ?it/s]/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [31,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [71,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [71,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [116,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [28,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [40,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [19,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [109,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [59,0,0], thread: [36,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [11,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [29,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [29,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [29,0,0], thread: [51,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [29,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [60,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [109,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [109,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [109,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [109,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [29,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [29,0,0], thread: [10,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [29,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [29,0,0], thread: [13,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [29,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [29,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [104,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [104,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [104,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [104,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [110,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [110,0,0], thread: [36,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [110,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [110,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [75,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [115,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [51,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [10,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [13,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [29,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [38,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [42,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [46,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [52,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [53,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [69,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [77,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [2,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [4,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [13,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [20,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [32,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [32,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [8,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [42,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [51,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [58,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [66,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [66,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [66,0,0], thread: [52,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [66,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [0,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [23,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [77,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [77,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [77,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [77,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [77,0,0], thread: [61,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [7,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [66,0,0], thread: [9,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [66,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [66,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [66,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [48,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [119,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [53,0,0], thread: [46,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [53,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [87,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [87,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [87,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [78,0,0], thread: [13,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [59,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [59,0,0], thread: [30,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [78,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [78,0,0], thread: [42,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [78,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [79,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [100,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [20,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [20,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [103,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [103,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [74,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [74,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [74,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [23,0,0], thread: [6,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [23,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [23,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [63,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [20,0,0], thread: [42,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [20,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [20,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [20,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [20,0,0], thread: [61,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [52,0,0], thread: [61,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [57,0,0], thread: [10,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [57,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [57,0,0], thread: [13,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [57,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [57,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [67,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [67,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [67,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [95,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [95,0,0], thread: [20,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [54,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [54,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [54,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [54,0,0], thread: [52,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [16,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [50,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [50,0,0], thread: [52,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [50,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [54,0,0], thread: [2,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [54,0,0], thread: [13,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [54,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [16,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [96,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [3,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [83,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [123,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [44,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [44,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
Traceback (most recent call last):
  File "main.py", line 278, in <module>
    main(args)
  File "main.py", line 33, in main
    net.train()
  File "/gpfsdswork/projects/rech/rjg/uiu23ko/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 764, in train
    loss.backward()
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
Exception raised from createCuDNNHandle at ../aten/src/ATen/cudnn/Handle.cpp:9 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x55 (0x14cf5d430fb5 in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x279fb98 (0x14cf6001fb98 in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #2: at::native::getCudnnHandle() + 0x1418 (0x14cf60021738 in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0x26840cd (0x14cf5ff040cd in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x267faf4 (0x14cf5feffaf4 in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x2683223 (0x14cf5ff03223 in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #6: at::native::cudnn_convolution_transpose_backward_input(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool) + 0xab (0x14cf5ff035db in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x26df7ed (0x14cf5ff5f7ed in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x270baba (0x14cf5ff8baba in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #9: at::cudnn_convolution_transpose_backward_input(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool) + 0x13a (0x14cf7208b4ea in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #10: at::native::cudnn_convolution_transpose_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x172 (0x14cf5feff462 in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #11: <unknown function> + 0x26df70b (0x14cf5ff5f70b in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #12: <unknown function> + 0x270bc1c (0x14cf5ff8bc1c in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #13: at::cudnn_convolution_transpose_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x1a7 (0x14cf72097727 in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x2d92808 (0x14cf73b7a808 in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x2da547c (0x14cf73b8d47c in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #16: at::cudnn_convolution_transpose_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x1a7 (0x14cf72097727 in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #17: torch::autograd::generated::CudnnConvolutionTransposeBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x279 (0x14cf739c42d9 in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #18: <unknown function> + 0x317e3db (0x14cf73f663db in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #19: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x1596 (0x14cf73f61b36 in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #20: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x4b1 (0x14cf73f62371 in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #21: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x8a (0x14cf73f5b23a in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #22: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x4e (0x14cf781fdc5e in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #23: <unknown function> + 0xc819d (0x14cf7ae8319d in /gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/libstdc++.so.6)
frame #24: <unknown function> + 0x82de (0x14cfbf8052de in /lib64/libpthread.so.0)
frame #25: clone + 0x43 (0x14cfbf536133 in /lib64/libc.so.6)

  1%|          | 1/100.0 [00:01<02:33,  1.55s/it]
+ wait
+ echo 'All done !'
