Loading pytorch-gpu/py3/1.6.0
  Loading requirement: gcc/8.3.1 cuda/10.2 nccl/2.6.4-1-cuda
    cudnn/7.6.5.32-cuda-10.2 intel-mkl/2020.1 magma/2.5.3-cuda
    openmpi/4.0.2-cuda
++ sed -n 6p parameters_combinations/mnist_classifier_ratio.txt
+ LINE='--gpu_devices 0 --max_iter 100 --batch_size 250 --use_scheduler True --lr 1e-3 --GMP True --z_struct_size 20 --is_VAE True --lambda_BCE 1 --beta 1 --big_kernel_size 8 --two_conv_layer True --three_conv_layer True --kernel_size_1 4 --kernel_size_2 4 --kernel_size_3 4 --BK_in_first_layer True --BK_in_second_layer False --BK_in_third_layer False --stride_size 1 --hidden_filters_layer1 64 --hidden_filters_layer2 64 --hidden_filters_layer3 64 --dataset_balanced True --binary_z True --binary_first_conv False --binary_second_conv False --binary_third_conv True --z_struct_size 10 --encoder_struct_name mnist_struct_baseline_scheduler_binary_20 --freeze_Encoder True --ES_reconstruction True --exp_name mnist_encoder_struct_reconstruction_s20_PT'
+ echo --gpu_devices 0 --max_iter 100 --batch_size 250 --use_scheduler True --lr 1e-3 --GMP True --z_struct_size 20 --is_VAE True --lambda_BCE 1 --beta 1 --big_kernel_size 8 --two_conv_layer True --three_conv_layer True --kernel_size_1 4 --kernel_size_2 4 --kernel_size_3 4 --BK_in_first_layer True --BK_in_second_layer False --BK_in_third_layer False --stride_size 1 --hidden_filters_layer1 64 --hidden_filters_layer2 64 --hidden_filters_layer3 64 --dataset_balanced True --binary_z True --binary_first_conv False --binary_second_conv False --binary_third_conv True --z_struct_size 10 --encoder_struct_name mnist_struct_baseline_scheduler_binary_20 --freeze_Encoder True --ES_reconstruction True --exp_name mnist_encoder_struct_reconstruction_s20_PT
+ python3 -u main.py --gpu_devices 0 --max_iter 100 --batch_size 250 --use_scheduler True --lr 1e-3 --GMP True --z_struct_size 20 --is_VAE True --lambda_BCE 1 --beta 1 --big_kernel_size 8 --two_conv_layer True --three_conv_layer True --kernel_size_1 4 --kernel_size_2 4 --kernel_size_3 4 --BK_in_first_layer True --BK_in_second_layer False --BK_in_third_layer False --stride_size 1 --hidden_filters_layer1 64 --hidden_filters_layer2 64 --hidden_filters_layer3 64 --dataset_balanced True --binary_z True --binary_first_conv False --binary_second_conv False --binary_third_conv True --z_struct_size 10 --encoder_struct_name mnist_struct_baseline_scheduler_binary_20 --freeze_Encoder True --ES_reconstruction True --exp_name mnist_encoder_struct_reconstruction_s20_PT
--- Logging error ---
Traceback (most recent call last):
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 611, in format
    s = self.formatMessage(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 580, in formatMessage
    return self._style.format(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 422, in format
    return self._fmt % record.__dict__
KeyError: 'asc_time'
Call stack:
  File "main.py", line 320, in <module>
    main(args)
  File "main.py", line 31, in main
    net = SolverClassifier(arguments)
  File "/gpfsdswork/projects/rech/rjg/uiu23ko/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 338, in __init__
    self.test_loader_size))
Message: 'Dataset mnist: train with 60000 samples and 10000 test samples'
Arguments: ()
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main(args)
  File "main.py", line 31, in main
    net = SolverClassifier(arguments)
  File "/gpfsdswork/projects/rech/rjg/uiu23ko/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 524, in __init__
    pre_trained_struct_model)
  File "/gpfsdswork/projects/rech/rjg/uiu23ko/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 939, in load_pre_trained_checkpoint
    model.load_state_dict(checkpoint['net'])
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Encoder_struct:
	size mismatch for encoder_struct.6.weight: copying a param with shape torch.Size([20, 64, 4, 4]) from checkpoint, the shape in current model is torch.Size([10, 64, 4, 4]).
	size mismatch for encoder_struct.6.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([10]).
	size mismatch for encoder_struct.7.weight: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([10]).
	size mismatch for encoder_struct.7.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([10]).
	size mismatch for encoder_struct.7.running_mean: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([10]).
	size mismatch for encoder_struct.7.running_var: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([10]).
	size mismatch for encoder_struct.11.weight: copying a param with shape torch.Size([10, 20]) from checkpoint, the shape in current model is torch.Size([10, 10]).
+ wait
+ echo 'All done !'
